- name: Deploy Restaurant App on EC2
  hosts: all
  become: true
  tasks:

    # Install Docker (if not already installed)
    - name: Install Docker
      apt:
        name: docker.io
        state: present
      become: true
      when: ansible_distribution == "Ubuntu"

    # Start Docker service
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true
      become: true

    # Debug Docker login environment variables
    - name: Debug Docker login environment variables
      debug:
        msg: "DOCKER_USERNAME={{ lookup('env', 'DOCKER_USERNAME') }}, DOCKER_PASSWORD={{ lookup('env', 'DOCKER_PASSWORD') }}"

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      shell: |
        echo "{{ lookup('env', 'DOCKER_PASSWORD') }}" | docker login -u "{{ lookup('env', 'DOCKER_USERNAME') }}" --password-stdin
      environment:
        DOCKER_USERNAME: "{{ lookup('env', 'DOCKER_USERNAME') }}"
        DOCKER_PASSWORD: "{{ lookup('env', 'DOCKER_PASSWORD') }}"

    # Pull the Docker image for the Restaurant App
    - name: Pull Restaurant App Docker image
      docker_image:
        name: "{{ docker_image_name }}"
        tag: latest
        source: pull
      become: true

    # Run the Docker container
    - name: Run Docker container for Restaurant App
      docker_container:
        name: restaurant-app
        image: "{{ docker_image_name }}:latest"
        state: started
        restart_policy: always
        published_ports:
          - "80:80"
      become: true
