---
- name: Deploy Restaurant Website on EC2
  hosts: web
  become: yes
  tasks:

    - name: Ensure website directory exists
      file:
        path: /home/ubuntu/restaurant-app
        state: directory

    - name: Copy website files
      copy:
        src: "{{ item }}"
        dest: /home/ubuntu/restaurant-app/
        mode: '0644'
      with_fileglob:
        - "../../*.html"
        - "../../*.css"
        - "../../*.js"

    - name: Set folder permissions
      file:
        path: /home/ubuntu/restaurant-app
        mode: '0755'
        recurse: yes

    - name: Create README on server
      copy:
        content: "This site is deployed using Ansible!"
        dest: /home/ubuntu/restaurant-app/README.txt

    - name: Show completion message
      debug:
        msg: "Restaurant Website successfully deployed using Ansible 🚀"
