---
- name: Deploy Restaurant Website on EC2
  hosts: all
  become: true

  tasks:
    # Install python3-apt to ensure apt module works
    - name: Install python3-apt
      apt:
        name: python3-apt
        state: present

    # Update apt cache and install Nginx
    - name: Update apt cache and install Nginx
      apt:
        update_cache: yes
        name:
          - nginx
        state: present

    # Start Nginx service
    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started
        enabled: yes

    # Clone the repository from GitHub to the EC2 instance
    - name: Clone the Restaurant application repository
      git:
        repo: 'https://github.com/yourusername/restaurant-app.git'  # Replace with your GitHub repo URL
        dest: /var/www/restaurant-app
        version: main  # Replace with your branch name
        force: yes

    # Copy the website files to Nginx's web root
    - name: Copy website files to Nginx web root
      copy:
        src: /var/www/restaurant-app
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: '0755'
        remote_src: yes

    # Restart Nginx to apply changes
    - name: Restart Nginx to apply changes
      service:
        name: nginx
        state: restarted
