---
- name: Deploy Restaurant App on EC2
  hosts: web
  become: true

  tasks:
    # Install Docker using dnf (for Amazon Linux 2023)
    - name: Install Docker
      dnf:
        name: docker
        state: present
        update_cache: yes

    # Start Docker service
    - name: Start Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    # Pull the latest Docker image of the restaurant app
    - name: Pull Restaurant App Docker image
      command: docker pull stutigambhir/restaurant-app:latest

    # Stop the existing container if it's running
    - name: Stop existing container
      shell: |
        docker ps -q --filter "name=restaurant-app" | grep -q . && docker stop restaurant-app || true

    # Remove the old container if it exists
    - name: Remove existing container
      shell: |
        docker ps -a -q --filter "name=restaurant-app" | grep -q . && docker rm restaurant-app || true

    # Run the container
    - name: Run Restaurant App container
      command: docker run -d -p 80:3000 --name restaurant-app stutigambhir/restaurant-app:latest
