---
- name: Install dependencies on the server
  hosts: web
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Python dependencies
      apt:
        name:
          - python3-pip
          - python3-dev
          - build-essential
        state: present

    - name: Install other system dependencies (optional)
      apt:
        name:
          - curl
          - git
        state: present
