name: Install Dependencies on EC2

on:
  push:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Add SSH Key to Known Hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 65.1.130.199 >> ~/.ssh/known_hosts

    - name: Create SSH key file
      run: |
        echo "${{ secrets.ANSIBLE_PRIVATE_KEY }}" > ~/stuti-key.pem
        chmod 600 ~/stuti-key.pem

    - name: Run Ansible Playbook to Install Dependencies
      run: |
        ansible-playbook -i ansible/inventory.ini ansible/install_dependencies.yml
