name: Deploy with Ansible

on:
  push:
    branches:
      - main

permissions:
  contents: read
  security-events: write

jobs:
  deploy:
    name: 🚀 Deploy to EC2 with Ansible
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Ansible
      - name: Set up Ansible
        run: sudo apt update && sudo apt install -y ansible

      # Create SSH key for EC2 access
      - name: Create SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > stuti-key.pem
          chmod 600 stuti-key.pem

      # Debug Docker credentials
      - name: Debug Docker Credentials
        run: |
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}"
          echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}"

      # Docker login (if using a private registry)
      - name: Docker Login (if needed)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Run Ansible Playbook
      - name: Run Ansible Playbook
        run: |
          ansible-playbook ansible/deploy.yml -i ansible/inventory.ini --private-key stuti-key.pem -u ${{ secrets.EC2_USER }}
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
