name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Run on the latest Ubuntu image
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Install dependencies with Ansible
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/install_dependencies.yml

      - name: Deploy application with Ansible
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/deploy.yml
